// script for outputing TeX source code used in CSCeff meeting slides
// Stephen Trembath-Reichert

#include <cstdio>
#include <string>
#include <fstream>

string Rings[] = {"ME-42", "ME-41",
		  "ME-32", "ME-31",
		  "ME-22", "ME-21",
		  "ME-13", "ME-12",
		  "ME-11B", "ME-11A",
		  "ME+11A", "ME+11B",
		  "ME+12", "ME+13",
		  "ME+21", "ME+22",
		  "ME+31", "ME+32",
		  "ME+41", "ME+42"};

const int PLOTROWS = 20; // 20
const int PLOTCOL1 = 18;
const int PLOTCOL2 = 36; // 36

void TeXoutput() {

  ofstream fout;
  fout.open("texout.txt");

  fout << "% BEGIN AUTOGENERATED FRAMES" << endl;

  for(int ybin = 1; ybin <= PLOTROWS; ybin++) {
      for(int xbin = 1; xbin <= PLOTCOL2; xbin += 2) {
	if(!((ybin == 2 || ybin == 4 || ybin == 6 || ybin == 15 || ybin == 17 || ybin == 19) && (xbin > 18))) {
	  fout << "\\frame{\\frametitle{"
	       << Rings[ybin - 1] << "-" << xbin << " and " 
	       << Rings[ybin - 1] << "-" << (xbin + 1)
	       << "}" << endl;
	  fout << "    \\begin{columns}[t]" << endl;
	  fout << "        \\column{.5\\textwidth}" << endl;
	  fout << "        \\centering" << endl;
	  fout << "        \\includegraphics[width=\\textwidth]{" 
	       << Rings[ybin - 1] << "-" << xbin 
	       << "_LCT.png}" << " \\" << "\\" << endl;
	  fout << "        \\includegraphics[width=\\textwidth]{" 
	       << Rings[ybin - 1] << "-" << xbin 
	       << "_SEG.png}" << endl;
	  fout << "        \\column{.5\\textwidth}" << endl;
	  fout << "        \\centering" << endl;
	  fout << "        \\includegraphics[width=\\textwidth]{" 
	       << Rings[ybin - 1] << "-" << (xbin + 1) 
	       << "_LCT.png}" << " \\" << "\\" << endl;
	  fout << "        \\includegraphics[width=\\textwidth]{" 
	       << Rings[ybin - 1] << "-" << (xbin + 1) 
	       << "_SEG.png}" << endl;
	  fout << "    \\end{columns}" << endl;
	  fout << "}" << endl << endl;
	}
      }
    }

}
